language: csharp
solution: "./Parser/Parser.sln"
install:
  - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./Parser/Parser.sln
  - nuget install NUnit.Runners -Version 3.11.0 -OutputDirectory testrunner
script:
  - xbuild ./Parser/Parser.sln
  - mono ./testrunner/NUnit.Runners.3.11.0/tools/nunit-console.exe ./Parser/Parser.Tests/bin/Debug/Parser.Tests.dll