version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
configuration: Release

before_build:
  - cd C:\projects\parser\Parser\
  - nuget restore Parser.sln

build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"Rassol_Parser" /d:sonar.organization="rassol-github" /d:"sonar.host.url=https://sonarqube.com" /d:sonar.login="96e5ae7a816be1b249709dc2e03edc37f37e0adc"
  - msbuild /t:Rebuild
  - MSBuild.SonarQube.Runner.exe end /d:sonar.login="96e5ae7a816be1b249709dc2e03edc37f37e0adc"
 
test_script:
- where nunit-console
- OpenCover.Console.exe -register:user -target:"C:\Tools\NUnit\bin\nunit-console.exe" -targetargs:".\Parser.Tests\bin\Release\Parser.Tests.dll -noshadow" -filter:"+[Parser*]* -[Parser.Tests*]*" -output:".\coverage.xml"
- codecov -f "coverage.xml

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t YourUploadToken