//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("UkrParserAssembly")]
[assembly: System.Reflection.AssemblyDescription("Parser for ukrainian criminal laws")]
[assembly: System.Reflection.AssemblyProduct("UkrParser")]
[assembly: System.Reflection.AssemblyCopyright("Copyright")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyInformationalVersion("v0.3-11-61469d079c8b6b089b5f1ff290399342db630c8e")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0")]


